[settings_paths]
; path location winrar
path_winrar = "C:\\Program Files\\WinRAR\\WinRAR.exe"
; get source from network
pathsource_network = "\\\\192.168.8.110\\BackupDB\\"
; copy file from pathsource_network to pathsource_device
pathsource_device = ".\\pathsource_device"
; extract (zip) file from pathsource_device to pathsource_extract
pathsource_extract = ".\\pathsource_extract"
; compress (zip) file from pathsource_extract to pathsource_compress
pathsource_archived = ".\\pathsource_archived"

; Config Dates
[settings_format]
; date format YYYY-MM-DD
date_format = "%Y-%m-%d"
; time format HH24-MM
time_format = "%H-%M"

[settings_dates]
date_source = "2024-06-01"
date_target = "2024-06-30"
